import React, { useState } from 'react';
import { Archive, ArchiveRestore, ChevronDown, ChevronUp, Pencil, Trash2 } from 'lucide-react';
import { ThoughtThread, MomentIntent } from '../types';
import { normalizeCompanionResponse } from '../logic/geminiProxyClient';

interface Props { thread: ThoughtThread; archived?: boolean; onAppend: (id: string, content: string, intent: MomentIntent) => Promise<void>; onArchive: () => Promise<void>; onRestore: () => Promise<void>; onDelete: () => Promise<void>; onEdit: (threadId: string, entryId: string, content: string) => Promise<void>; }
const intentLabel: Record<MomentIntent, string> = { captured: '', reappeared: '又想到', follow_up: '有後續', context_added: '補充' };
const date = (stamp: number) => new Intl.DateTimeFormat('zh-TW', { month: 'numeric', day: 'numeric' }).format(new Date(stamp));
const time = (stamp: number) => new Intl.DateTimeFormat('zh-TW', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(stamp));

export const ThoughtCard: React.FC<Props> = ({ thread, archived = false, onAppend, onArchive, onRestore, onDelete, onEdit }) => {
  const [expanded, setExpanded] = useState(true); const [adding, setAdding] = useState(false); const [intent, setIntent] = useState<MomentIntent>('reappeared'); const [text, setText] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [editText, setEditText] = useState('');
  const entries = [...thread.entries].sort((a,b)=>a.createdAt-b.createdAt);
  const save = async () => { if (!text.trim()) return; await onAppend(thread.id, text, intent); setText(''); setAdding(false); };
  return <section className="relative border-l border-accent/25 pl-5 pb-2">
    <span className="absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full bg-accent ring-4 ring-canvas"/>
    <div className="flex items-start justify-between gap-3"><button onClick={()=>setExpanded(value=>!value)} className="text-left"><p className="text-xs text-ink-muted">從 {date(thread.createdAt)} 開始 · {entries.length} 個片段</p><p className="text-base text-ink mt-1 leading-relaxed">{entries[0]?.content}</p></button><button onClick={()=>setExpanded(value=>!value)} className="p-1 text-ink-muted">{expanded ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</button></div>
    {expanded && <div className="mt-4 space-y-4">{entries.map((entry, index) => <div key={entry.id} className="relative pl-4 border-l border-border-subtle"><div className="flex items-center gap-2 text-xs text-ink-muted"><span>{date(entry.createdAt)} {time(entry.createdAt)}</span>{entry.intent && intentLabel[entry.intent] && <span className="rounded-full bg-surface-subtle px-2 py-0.5">{intentLabel[entry.intent]}</span>}</div>{editing===entry.id ? <div className="mt-2"><textarea value={editText} onChange={e=>setEditText(e.target.value)} className="w-full rounded-xl bg-surface border border-border-base p-2 text-sm outline-none"/><div className="mt-2 flex gap-2"><button onClick={async()=>{await onEdit(thread.id,entry.id,editText);setEditing(null);}} className="text-xs text-accent">儲存</button><button onClick={()=>setEditing(null)} className="text-xs text-ink-muted">取消</button></div></div> : <><button onClick={()=>{setEditing(entry.id);setEditText(entry.content);}} className="group text-left mt-1 flex gap-2"><p className="text-[16px] leading-relaxed text-ink whitespace-pre-wrap">{entry.content}</p>{index===entries.length-1 && <Pencil size={12} className="opacity-0 group-hover:opacity-50 mt-1"/>}</button>{entry.aiResponse && <p className="mt-2 rounded-xl bg-accent/5 px-3 py-2 text-sm leading-relaxed text-ink-secondary">{normalizeCompanionResponse(entry.aiResponse)}</p>}</>}</div>)}</div>}
    {!archived && !adding && <button onClick={()=>setAdding(true)} className="mt-4 text-sm text-ink-secondary hover:text-ink">＋ 記下後來發生的事</button>}
    {adding && <div className="mt-4 rounded-2xl bg-surface-subtle p-3"><div className="flex gap-2 mb-2">{(['reappeared','follow_up','context_added'] as MomentIntent[]).map(key=><button key={key} onClick={()=>setIntent(key)} className={`text-xs px-2.5 py-1 rounded-full ${intent===key?'bg-accent text-accent-text':'bg-surface text-ink-secondary'}`}>{intentLabel[key]}</button>)}</div><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="留下一句就好……" className="w-full bg-transparent outline-none resize-none text-sm text-ink" rows={2}/><div className="flex gap-3 mt-2"><button onClick={()=>void save()} className="text-xs text-accent">停靠</button><button onClick={()=>setAdding(false)} className="text-xs text-ink-muted">取消</button></div></div>}
    <div className="mt-5 flex gap-3 text-xs text-ink-muted">{archived ? <><button onClick={()=>void onRestore()} className="flex items-center gap-1 hover:text-ink"><ArchiveRestore size={13}/>放回眼前</button><button onClick={()=>void onDelete()} className="flex items-center gap-1 hover:text-ink"><Trash2 size={13}/>讓它消失</button></> : <button onClick={()=>void onArchive()} className="flex items-center gap-1 hover:text-ink"><Archive size={13}/>先別再浮出</button>}</div>
  </section>;
};
